/*---------------------------------------------------------------------------*\
  File: createFields.H
  Part of: SoPLASMA
  Developed using the OpenFOAM framework and linked against OpenFOAM libraries.

  Description:
      Derived from createFields.H in OpenFOAM v2412.
      Defines and initializes fields that are not defined by the models but 
      are required for the solver.

  Copyright (C) 2026 Rention Pasolari
  License: GNU General Public License v3 or later
      See: <http://www.gnu.org/licenses/>.
\*---------------------------------------------------------------------------*/

// For now, all fields are created by the models, so this file is empty
