#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -r 0

rm Emax_vs_time.dat

rm -r logs

rm log.*

rm *.txt

rm -r dynamicCode




