/*---------------------------------------------------------------------------*\
  File: SoPLASMAConstants.H
  Part of: SoPLASMA

  Description:
      Aggregated header including all physical constants defined within the
      SoPLASMA. 

  Namespace:
      Foam::constant

  Copyright (C) 2025 Rention Pasolari
  License: GNU General Public License v3 or later
      See: <http://www.gnu.org/licenses/>.
\*---------------------------------------------------------------------------*/

#ifndef SoPLASMAConstants_H
#define SoPLASMAConstants_H

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#include "plasmaConstants.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
