#------------------------------------------------------------------------------#
#  File: bashrc
#  Part of: SoPLASMA
#  Developed for use with the OpenFOAM framework.
#
#  Description:
#      Environment setup script for SoPLASMA.
#
#  Author: Rention Pasolari
#  Copyright (C) 2025
#  License: GNU General Public License v3 or later
#      See: <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------#

# Determine SoPLASMA root directory (one level above this file)
export SoPLASMA=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
alias SoPLASMA='cd "$SoPLASMA"'

export SoPLASMA_ETC="$SoPLASMA/etc"

export SoPLASMA_TUTORIALS="$SoPLASMA/tutorials"

export SoPLASMA_SRC="$SoPLASMA/src"

export SoPLASMA_THIRD_PARTY="$SoPLASMA/ThirdParty"
