#------------------------------------------------------------------------------#
#  File: bashrc
#  Part of: SoPLASMA
#  Developed for use with the OpenFOAM framework.
#
#  Description:
#      Environment setup script for SoPLASMA.
#
#  Author: Rention Pasolari
#  Copyright (C) 2025
#  License: GNU General Public License v3 or later
#      See: <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------#

# Determine SoPLASMA root directory (one level above this file)
export FOAM_PLASMA=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
alias SoPLASMA='cd "$FOAM_PLASMA"'

export FOAM_PLASMA_ETC="$FOAM_PLASMA/etc"

export FOAM_PLASMA_TUTORIALS="$FOAM_PLASMA/tutorials"

export FOAM_PLASMA_SRC="$FOAM_PLASMA/src"

export FOAM_PLASMA_THIRD_PARTY="$FOAM_PLASMA/ThirdParty"
