#------------------------------------------------------------------------------#
#  File: bashrc
#  Part of: SoPLASMA
#  Developed for use with the OpenFOAM framework.
#
#  Description:
#      Environment setup script for SoPLASMA.
#
#  Author: Rention Pasolari
#  Copyright (C) 2025
#  License: GNU General Public License v3 or later
#      See: <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------#

# Determine SoPLASMA root directory (one level above this file)
export So_PLASMA=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
alias SoPLASMA='cd "$So_PLASMA"'

export So_PLASMA_ETC="$So_PLASMA/etc"

export So_PLASMA_TUTORIALS="$So_PLASMA/tutorials"

export So_PLASMA_SRC="$So_PLASMA/src"

export So_PLASMA_THIRD_PARTY="$So_PLASMA/ThirdParty"
