#!/bin/bash

#---------------------------------------------
#  Allwmake script for SoPLASMA suite
#  Builds all models in src/models
#---------------------------------------------

set -e

# Move to the directory where this script is located
cd "${0%/*}" || exit 1

echo ">>> Building models in src/models"
echo "----------------------------------------------"

wmake libso ./electromagnetics/
./plasmaModels/Allwmake

echo ">>> Done building models."
echo "----------------------------------------------"
