/*---------------------------------------------------------------------------*\
License
    This file is part of the SoPLASMA.

    The SoPLASMA is not part of OpenFOAM but is developed using the
    OpenFOAM framework and linked against OpenFOAM libraries.

    Copyright (C) 2026 Rention Pasolari

    This program is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation, either version 3 of the License, or (at your
    option) any later version.

    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::plasmaWallBC

Description
    Abstract wall boundary condition interface. Serves as a base for all
    SoPLASMA wall boundary conditions that need to support surface charging.
    All wall BCs derive from this so they can be found via dynamic_cast
    using this type.
    
\*---------------------------------------------------------------------------*/

#ifndef plasmaWallBC_H
#define plasmaWallBC_H

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                        Class plasmaWallBC Declaration
\*---------------------------------------------------------------------------*/

class plasmaWallBC
{
public:

    //- Destructor
    virtual ~plasmaWallBC() = default;

    // Wall properties
    virtual bool enableSurfaceCharging() const
    {
        return false;
    }

};

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
